# Set width and height
DISPLAY_WIDTH  =  1500
DISPLAY_HEIGHT =  1000

#Rackets
RACKET_WIDTH  = 50
RACKET_HEIGHT = 200
RACKET_HALF_HEIGHT = RACKET_HEIGHT/2
RACKET_OFFSET       = 50
RACKET_START_HEIGHT = DISPLAY_HEIGHT/2 - RACKET_HEIGHT/2
NUM_RACKET_REDIRECT_LINES_PER_HALF = 5
NUM_RACKET_REDIRECT_ANGLES = NUM_RACKET_REDIRECT_LINES_PER_HALF*2 + 1
DISTANCE_BETWEEN_REDIRECT = RACKET_HEIGHT/NUM_RACKET_REDIRECT_ANGLES
START_ANGLE  = 70
ANGLE_CHANGE = START_ANGLE/NUM_RACKET_REDIRECT_LINES_PER_HALF

#Pong
PONG_RADIUS   = 20
PONG_START_X  = DISPLAY_WIDTH/2   - PONG_RADIUS/2
PONG_START_Y  = DISPLAY_HEIGHT/2  - PONG_RADIUS/2
PONG_SPEED    = 20

#Border
BORDER_X = DISPLAY_WIDTH/2
BORDER_Y = 50
BORDER_WIDTH   = 10
BORDER_HEIGHT = 20


#Score
SCORE_CENTER_OFFSET = 100
COMPUTER_SCORE_X    = DISPLAY_WIDTH/2 - SCORE_CENTER_OFFSET
HUMAN_SCORE_X       = DISPLAY_WIDTH/2 + SCORE_CENTER_OFFSET
SCORE_Y             = 100


WALL_LINE = 50
WALL_SCORE_LEFT  = WALL_LINE
WALL_SCORE_RIGHT = DISPLAY_WIDTH - WALL_LINE


