# Set width and height
DISPLAY_WIDTH  =  1500
DISPLAY_HEIGHT =  1000

#Rackets
RACKET_WIDTH  = 50
RACKET_HEIGHT = 200
RACKET_OFFSET       = 50
RACKET_START_HEIGHT = DISPLAY_HEIGHT/2 - RACKET_HEIGHT/2

#Pong
PONG_RADIUS   = 20
PONG_START_X  = DISPLAY_WIDTH/2   - PONG_RADIUS/2
PONG_START_Y  = DISPLAY_HEIGHT/2  - PONG_RADIUS/2

#Border
BORDER_X = DISPLAY_WIDTH/2
BORDER_Y = 50
BORDER_WIDTH   = 10
BORDER_HEIGHT = 20
